# 트리거 : PUSH, PR(pull request) 이벤트 발생시 작동, 브런치는 main(없으면 master)
# 만약, 프런트, 백엔드 통합 => 특정 디렉토리가 업데이트 될때 반영해라 등 세부 조건 추가 가능
on:
    push:
      branches:
        - main
    pull_request:
      branches:
       - main

jobs:
    react-deploy:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repository resoures
            uses: actions/checkout@v2
          - name: .env 환경 변수 동적 생성
            run: |
                echo "${{secrets.CLIENT_ENV}}" > .env
                pwd
                ls -al
            
